# Generated by Django 6.0.3 on 2026-05-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('hobie', models.CharField(max_length=200)),
                ('gosta_chocolate', models.BooleanField(default=True)),
            ],
        ),
    ]
