# Generated by Django 6.0.5 on 2026-05-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='hobie',
            new_name='hobbie',
        ),
        migrations.AddField(
            model_name='formulario',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='kobo_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
